- name: 'logrotate | install'
  apt: name='{{item}}'
  with_items:
    - logrotate

- name: 'logrotate | copy config'
  template:
    src: pr30_logrotate
    dest: /etc/logrotate.d/pr30
    owner: root
    group: root
    mode: 0644

- lineinfile:
    path: /etc/crontab
    regexp: 'cron.daily'
    line: '00 0    * * *   root    test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )'
  tags: cron